//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterStudent", ReplyAction="http://tempuri.org/IService1/RegisterStudentResponse")]
        bool RegisterStudent(string fname, string sname, string idNo, string email, string phone, string gender, string institution, string course, string level, string funding, string sNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterStudent", ReplyAction="http://tempuri.org/IService1/RegisterStudentResponse")]
        System.Threading.Tasks.Task<bool> RegisterStudentAsync(string fname, string sname, string idNo, string email, string phone, string gender, string institution, string course, string level, string funding, string sNumber, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        int Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetrieveFunding", ReplyAction="http://tempuri.org/IService1/RetrieveFundingResponse")]
        string RetrieveFunding(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RetrieveFunding", ReplyAction="http://tempuri.org/IService1/RetrieveFundingResponse")]
        System.Threading.Tasks.Task<string> RetrieveFundingAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SingleRoomPrice", ReplyAction="http://tempuri.org/IService1/SingleRoomPriceResponse")]
        double SingleRoomPrice(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SingleRoomPrice", ReplyAction="http://tempuri.org/IService1/SingleRoomPriceResponse")]
        System.Threading.Tasks.Task<double> SingleRoomPriceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TwosRoomPrice", ReplyAction="http://tempuri.org/IService1/TwosRoomPriceResponse")]
        double TwosRoomPrice(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TwosRoomPrice", ReplyAction="http://tempuri.org/IService1/TwosRoomPriceResponse")]
        System.Threading.Tasks.Task<double> TwosRoomPriceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThreeRoomPrice", ReplyAction="http://tempuri.org/IService1/ThreeRoomPriceResponse")]
        double ThreeRoomPrice(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ThreeRoomPrice", ReplyAction="http://tempuri.org/IService1/ThreeRoomPriceResponse")]
        System.Threading.Tasks.Task<double> ThreeRoomPriceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FourRoomPrice", ReplyAction="http://tempuri.org/IService1/FourRoomPriceResponse")]
        double FourRoomPrice(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FourRoomPrice", ReplyAction="http://tempuri.org/IService1/FourRoomPriceResponse")]
        System.Threading.Tasks.Task<double> FourRoomPriceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FiveRoomPrice", ReplyAction="http://tempuri.org/IService1/FiveRoomPriceResponse")]
        double FiveRoomPrice(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/FiveRoomPrice", ReplyAction="http://tempuri.org/IService1/FiveRoomPriceResponse")]
        System.Threading.Tasks.Task<double> FiveRoomPriceAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retriveUserName", ReplyAction="http://tempuri.org/IService1/retriveUserNameResponse")]
        string retriveUserName(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retriveUserName", ReplyAction="http://tempuri.org/IService1/retriveUserNameResponse")]
        System.Threading.Tasks.Task<string> retriveUserNameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/paymentStatus", ReplyAction="http://tempuri.org/IService1/paymentStatusResponse")]
        int paymentStatus(int id, double amount, double owing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/paymentStatus", ReplyAction="http://tempuri.org/IService1/paymentStatusResponse")]
        System.Threading.Tasks.Task<int> paymentStatusAsync(int id, double amount, double owing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatePayment", ReplyAction="http://tempuri.org/IService1/updatePaymentResponse")]
        void updatePayment(int id, double amount, double owing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/updatePayment", ReplyAction="http://tempuri.org/IService1/updatePaymentResponse")]
        System.Threading.Tasks.Task updatePaymentAsync(int id, double amount, double owing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendApplication", ReplyAction="http://tempuri.org/IService1/sendApplicationResponse")]
        bool sendApplication(int id, string name, string roomtype, string discount, string fee, string paymentStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendApplication", ReplyAction="http://tempuri.org/IService1/sendApplicationResponse")]
        System.Threading.Tasks.Task<bool> sendApplicationAsync(int id, string name, string roomtype, string discount, string fee, string paymentStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkId", ReplyAction="http://tempuri.org/IService1/checkIdResponse")]
        bool checkId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/checkId", ReplyAction="http://tempuri.org/IService1/checkIdResponse")]
        System.Threading.Tasks.Task<bool> checkIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecordInvoice", ReplyAction="http://tempuri.org/IService1/RecordInvoiceResponse")]
        bool RecordInvoice(int id, string name, string discount, string roomtype, string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecordInvoice", ReplyAction="http://tempuri.org/IService1/RecordInvoiceResponse")]
        System.Threading.Tasks.Task<bool> RecordInvoiceAsync(int id, string name, string discount, string roomtype, string amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Project.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Project.ServiceReference2.IService1>, Project.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegisterStudent(string fname, string sname, string idNo, string email, string phone, string gender, string institution, string course, string level, string funding, string sNumber, string password) {
            return base.Channel.RegisterStudent(fname, sname, idNo, email, phone, gender, institution, course, level, funding, sNumber, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterStudentAsync(string fname, string sname, string idNo, string email, string phone, string gender, string institution, string course, string level, string funding, string sNumber, string password) {
            return base.Channel.RegisterStudentAsync(fname, sname, idNo, email, phone, gender, institution, course, level, funding, sNumber, password);
        }
        
        public int Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
        
        public string RetrieveFunding(int id) {
            return base.Channel.RetrieveFunding(id);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveFundingAsync(int id) {
            return base.Channel.RetrieveFundingAsync(id);
        }
        
        public double SingleRoomPrice(int id) {
            return base.Channel.SingleRoomPrice(id);
        }
        
        public System.Threading.Tasks.Task<double> SingleRoomPriceAsync(int id) {
            return base.Channel.SingleRoomPriceAsync(id);
        }
        
        public double TwosRoomPrice(int id) {
            return base.Channel.TwosRoomPrice(id);
        }
        
        public System.Threading.Tasks.Task<double> TwosRoomPriceAsync(int id) {
            return base.Channel.TwosRoomPriceAsync(id);
        }
        
        public double ThreeRoomPrice(int id) {
            return base.Channel.ThreeRoomPrice(id);
        }
        
        public System.Threading.Tasks.Task<double> ThreeRoomPriceAsync(int id) {
            return base.Channel.ThreeRoomPriceAsync(id);
        }
        
        public double FourRoomPrice(int id) {
            return base.Channel.FourRoomPrice(id);
        }
        
        public System.Threading.Tasks.Task<double> FourRoomPriceAsync(int id) {
            return base.Channel.FourRoomPriceAsync(id);
        }
        
        public double FiveRoomPrice(int id) {
            return base.Channel.FiveRoomPrice(id);
        }
        
        public System.Threading.Tasks.Task<double> FiveRoomPriceAsync(int id) {
            return base.Channel.FiveRoomPriceAsync(id);
        }
        
        public string retriveUserName(int id) {
            return base.Channel.retriveUserName(id);
        }
        
        public System.Threading.Tasks.Task<string> retriveUserNameAsync(int id) {
            return base.Channel.retriveUserNameAsync(id);
        }
        
        public int paymentStatus(int id, double amount, double owing) {
            return base.Channel.paymentStatus(id, amount, owing);
        }
        
        public System.Threading.Tasks.Task<int> paymentStatusAsync(int id, double amount, double owing) {
            return base.Channel.paymentStatusAsync(id, amount, owing);
        }
        
        public void updatePayment(int id, double amount, double owing) {
            base.Channel.updatePayment(id, amount, owing);
        }
        
        public System.Threading.Tasks.Task updatePaymentAsync(int id, double amount, double owing) {
            return base.Channel.updatePaymentAsync(id, amount, owing);
        }
        
        public bool sendApplication(int id, string name, string roomtype, string discount, string fee, string paymentStatus) {
            return base.Channel.sendApplication(id, name, roomtype, discount, fee, paymentStatus);
        }
        
        public System.Threading.Tasks.Task<bool> sendApplicationAsync(int id, string name, string roomtype, string discount, string fee, string paymentStatus) {
            return base.Channel.sendApplicationAsync(id, name, roomtype, discount, fee, paymentStatus);
        }
        
        public bool checkId(int id) {
            return base.Channel.checkId(id);
        }
        
        public System.Threading.Tasks.Task<bool> checkIdAsync(int id) {
            return base.Channel.checkIdAsync(id);
        }
        
        public bool RecordInvoice(int id, string name, string discount, string roomtype, string amount) {
            return base.Channel.RecordInvoice(id, name, discount, roomtype, amount);
        }
        
        public System.Threading.Tasks.Task<bool> RecordInvoiceAsync(int id, string name, string discount, string roomtype, string amount) {
            return base.Channel.RecordInvoiceAsync(id, name, discount, roomtype, amount);
        }
    }
}
