// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Team8WebAPI.data;

#nullable disable

namespace Team8WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230728051247_UsersEntity")]
    partial class UsersEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Team44WebAPI.Models.Users", b =>
                {
                    b.Property<int>("U_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("U_ID"), 1L, 1);

                    b.Property<string>("U_CellNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("U_ID");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
